# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Country.create(country_name: 'Australia')
Country.create(country_name: 'Austria')
Country.create(country_name: 'Belgium')
Country.create(country_name: 'Brazil')
Country.create(country_name: 'Cambodia')
Country.create(country_name: 'Canada')
Country.create(country_name: 'China')
Country.create(country_name: 'Denmark')
Country.create(country_name: 'Egypt')
Country.create(country_name: 'Ethiopia')
Country.create(country_name: 'Fiji')
Country.create(country_name: 'Finland')
Country.create(country_name: 'France')
Country.create(country_name: 'Gremany')
Country.create(country_name: 'Finland')
Country.create(country_name: 'Greece')
Country.create(country_name: 'Finland')
Country.create(country_name: 'India')
Country.create(country_name: 'Indonesia')
Country.create(country_name: 'Japan')
Country.create(country_name: 'Mexico')
Country.create(country_name: 'Morocco')
Country.create(country_name: 'Nepal')
Country.create(country_name: 'New Zealand')
Country.create(country_name: 'Norway')
Country.create(country_name: 'Philippines')
Country.create(country_name: 'Porland')
Country.create(country_name: 'Korea')
Country.create(country_name: 'Spain')
Country.create(country_name: 'Sweden')
Country.create(country_name: 'Switzerland')
Country.create(country_name: 'Thailand')
Country.create(country_name: 'Turkey')
Country.create(country_name: 'United Kingdom')
Country.create(country_name: 'United States')
Country.create(country_name: 'Vietnam')

City.create(city_name: 'Tokyo', country_id: 20, photographer_id: 1)
